export const START_COMMENTS_LOADING = "START_COMMENTS_LOADING";
export const STOP_COMMENTS_LOADING = "STOP_COMMENTS_LOADING";
export const SET_COMMENTS = "SET_COMMENTS";
export const SET_COMMENTS_ERROR = "SET_COMMENTS_ERROR";