export const START_POSTS_LOADING = "START_POSTS_LOADING";
export const STOP_POSTS_LOADING = "STOP_POSTS_LOADING";
export const SET_POSTS = "SET_POSTS";
export const SET_POSTS_ERROR = "SET_POSTS_ERROR";